services:
  # MySQL 8.0
#  docker compose up -d mysql
#  docker stats --no-stream mysql8
  mysql:
    image: docker.m.daocloud.io/mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 59de91a6479c434abc13354e225b8fa6
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

# 创建共享网络
networks:
  app-network:
    driver: bridge
    name: app-network

# 数据卷持久化
volumes:
  mysql_data:
  redis_data:
  clickhouse_data:
  clickhouse_logs:
  rabbitmq_data:
  ollama_data: